### ISSUE TITLE
Dark Souls 3 Crash report "Remaining size of stream was smaller than requested number of bytes"

### ISSUE THREAD

**Issue by AaronMcDaniel** [Jacks8n/StraySouls#2]
I keep getting the following error when trying to randomize DS3:
`Unhandled Exception: System.IO.EndOfStreamException: Remaining size of stream was smaller than requested number of bytes.   at SoulsFormats.BinaryReaderEx.ReadBytes(Int32 count)
   at SoulsFormats.BinaryReaderEx.AssertASCII(String[] values)
   at SoulsFormats.MSB3.Read(BinaryReaderEx br)
   at SoulsFormats.SoulsFile`1.Read(String path)
   at StraySouls.Input.EnemyRandomCommand_DS3.Execute(String filePath, String fileName)
   at StraySouls.Input.CommandInput.Command(String input)   at StraySouls.Program.Main(String[] args)
`
Is there a way around this or will it require a patch or me reinstalling DS3 to fix?

**Comment by AaronMcDaniel** [comment]
Also I forgot to mention that my game crashes on start up. The crashing started around the same time as the error, but I'm not sure if the crashing was caused by the randomization error or if the crashing caused the the randomization error.

**Comment by AaronMcDaniel** [comment]
I fixed this by using the vanilla maps found in the [enemy onslaught mod](https://www.nexusmods.com/darksouls3/mods/296/).
